package com.L2.mvci_settings;

public enum SettingsMessage {
    SAVE_ENTITLEMENTS,
    PRINT_ENTITLEMENTS,
    SHOW_USER,
    SHOW_ENTITLEMENTS,
    SAVE_USER,
    SELECT_AFTER,
    SELECT_PREVIOUS,
    DELETE_ENTITLEMENT,
    NEW_ENTITLEMENT
}
