package com.L2.mvci_settings;

public enum SettingsMessage {
    SAVE_ENTITLEMENTS,
    PRINT_ENTITLEMENTS,
    SHOW_USER,
    SHOW_ENTITLEMENTS,
    SAVE_USER,
    SELECT_AFTER,
    SELECT_PREVIOUS,
    DELETE_ENTITLEMENT,
    MAKE_REFERENCE_TO_USER, REFRESH_ENTITLEMENT_COMBO_BOX, SHOW_DICTIONARY, TOGGLE_SPELLCHECK, SHOW_GLOBAL_SPARES, CONVERT_XLSX_TO_SQL, NEW_ENTITLEMENT
}
