package com.L2.mvci_notelist;

public enum NoteListMessage {
    REFERENCE_BOUND_NOTE_PROPERTY, UPDATE_BOUND_NOTE, SAVE_OR_UPDATE_NOTE, SELECT_BOUND_NOTE_IN_TABLE, REFRESH_NOTE_TABLEVIEW, REFERENCE_NOTES

}