package com.L2.mvci_notelist;

public enum NoteListMessage {
    REFERENCE_BOUND_NOTE_PROPERTY,
    UPDATE_BOUND_NOTE,
    SAVE_OR_UPDATE_NOTE,
    SORT_NOTE_TABLEVIEW,
    SELECT_NOTE_TAB,
    REFRESH_NOTE_TABLEVIEW,
    CHECK_BUTTON_ENABLE,
    NEXT_NOTE,
    PREVIOUS_NOTE,
    SELECT_NOTE_IN_LIST_AND_SELECT_TABLEROW_WITH_IT, REFERENCE_PAGE_SIZE, REFERENCE_OFFSET, REFERENCE_NOTES
}