package com.L2.mvci.notelist;

public enum NoteListMessage {
    REFERENCE_BOUND_NOTE_PROPERTY,
    UPDATE_BOUND_NOTE,
    SAVE_OR_UPDATE_NOTE,
    SORT_NOTE_TABLEVIEW,
    SELECT_NOTE_TAB,
    REFRESH_NOTE_TABLEVIEW,
    CHECK_BUTTON_ENABLE,
    NEXT_NOTE,
    PREVIOUS_NOTE,
    SELECT_NOTE_IN_LIST_AND_SELECT_TABLEROW_WITH_IT, REFERENCE_PAGE_SIZE, REFERENCE_OFFSET, ADD_TO_BOTTOM_OF_LIST, ADD_TO_TOP_OF_LIST, SEARCH, UPDATE_RANGE_LABEL, UPDATE_TABLE, NO_ACTION_TAKEN_FOR_SEARCH, NO_ACTION_TAKEN_FOR_SCROLL, NO_ACTION_TAKEN_FOR_KEY_PRESS, SHUT_DOWN_EXECUTOR, REFERENCE_NOTES
}