package com.L2.mvci_main;

public enum MainMessage {
    CLOSE_ALL_CONNECTIONS,
    CLOSE_ALL_CONNECTIONS_AND_EXIT,
    CREATE_CONNECT_CONTROLLER,
    BACKUP_DATABASE,
    PRIMARY_STAGE_COMPLETE,
    SELECT_TAB,
    SHOW_LOG,
    NONE
}