package com.L2.mvci_main;

public enum MainMessage {
    OPEN_NOTES,
    OPEN_SETTINGS,
    PRIMARY_STAGE_COMPLETE,
    SELECT_TAB,
    SHOW_LOG,
    PREVIOUS_NOTE,
    NEXT_NOTE,
    SET_COMPLETE,
    NEW_NOTE,
    SAVE_OR_UPDATE_NOTE,
    TEST, OPEN_NOTES_LIST,
    SELECT_BOUND_NOTE_IN_TABLE,
    REFRESH_NOTE_TABLEVIEW,
    UPDATE_NOTE_TAB_NAME,
    CLONE_NOTE, DELETE_NOTE,
    SELECT_NOTE_TAB,
    UPDATE_BOUND_NOTE,
    NONE,
    UPDATE_STATUSBAR
}