package com.L2.mvci_main;

public enum MainMessage {
    OPEN_NOTES,
    OPEN_SETTINGS,
    PRIMARY_STAGE_COMPLETE,
    SELECT_TAB,
    SHOW_LOG,
    PREVIOUS_NOTE, NEXT_NOTE, SET_COMPLETE, NEW_NOTE, SAVE_NOTE, TEST, NONE
}