package com.L2.mvci.note.mvci.partorderbox.mvci.partfinder;

public enum PartFinderMessage {
    SET_SELECTED_RANGE,
    SAVE_PART_NOTE,
    CANCEL_NOTE_UPDATE,
    SAVE_PIM_TO_JSON,
    REFRESH_TREEVIEW,
    SAVE_PART_KEYWORDS,
    CANCEL_KEYWORD_UPDATE,
    SAVE_IMAGE_TO_DATABASE,
    LOAD_IMAGE,
    SAVE_EDIT_HISTORY,
    GET_UPDATE_BY_INFORMATION,
    REFRESH_PART_INFO,
    TEST_SOME_SHIT, JSON_MAP_PRODUCT_FAMILIES
}
