package com.L2.mvci_note;

public enum NoteMessage {
    STATUS_BAR_CHANGE,
    REPORT_NUMBER_OF_PART_ORDERS,
    COPY_PART_ORDER,
    LOAD_USER,
    COPY_NAME_DATE,
    SHIPPING_INFORMATION,
    COPY_BASIC_INFORMATION,
    COPY_CUSTOMER_REQUEST,
    COPY_ISSUE,
    COPY_CORRECTIVE_ACTION,
    SET_COMPLETE, NEW_NOTE, LOG_CURRENT_ENTITLEMENT, PREVIOUS_NOTE, NEXT_NOTE, SAVE_NOTE, LOG_ORDER_NUMBER_CHANGE
}
