package com.L2.mvci_note;

public enum NoteMessage {
    STATUS_BAR_CHANGE,
    REPORT_NUMBER_OF_PART_ORDERS,
    COPY_PART_ORDER,
    LOAD_USER,
    COPY_NAME_DATE, SITE_INFORMATION, COPY_BASIC_INFORMATION, COPY_CUSTOMER_REQUEST, COPY_ISSUE, LOG_ORDER_NUMBER_CHANGE
}
